-- Create active_shift table to track global shift state
CREATE TABLE IF NOT EXISTS position_shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_label TEXT NOT NULL CHECK (shift_label IN ('MORNING', 'AFTERNOON')),
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  changed_by UUID REFERENCES auth.users(id),
  changed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- We only really need one active record for the current state, 
-- but keeping history is good. We can use a view or function to get the latest.
-- Or better, a single row table for "current state" config? 
-- The user requested 'active_shift' table with date/shift_label. 
-- Let's stick to a log-based approach where the latest entry for the date is the truth.

-- Enable RLS
ALTER TABLE position_shifts ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read (needed for login)
CREATE POLICY "Allow public read access" ON position_shifts FOR SELECT USING (true);

-- Allow admins to insert/update
-- Assuming we identify admins via a metadata check or existing role check
-- For now, allow authenticated users to read, but we will handle logic in app.
-- Ideally, only admins can inserting.
CREATE POLICY "Allow admin insert" ON position_shifts FOR INSERT WITH CHECK (true); 


-- Create staff_shifts table
CREATE TABLE IF NOT EXISTS staff_shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES users(id) NOT NULL, -- References our public users table
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  shift_label TEXT NOT NULL CHECK (shift_label IN ('MORNING', 'AFTERNOON')),
  role TEXT NOT NULL CHECK (role IN ('ADMIN', 'RECEPTIONIST', 'SCANNER', 'OFF')),
  status TEXT DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, date, shift_label)
);

-- Enable RLS
ALTER TABLE staff_shifts ENABLE ROW LEVEL SECURITY;

-- Allow everyone to read (needed for login check)
CREATE POLICY "Allow public read access staff_shifts" ON staff_shifts FOR SELECT USING (true);

-- Allow admins to insert/update (upsert)
CREATE POLICY "Allow admin all staff_shifts" ON staff_shifts FOR ALL USING (true);


-- Initial Data Seeding (Optional - DO NOT RUN if you want clean slate)
-- INSERT INTO position_shifts (shift_label, date) VALUES ('MORNING', CURRENT_DATE);
