-- Weekly Schedules Table
-- Tracks recurring roles for every staff member for each day of the week (1=Monday, 7=Sunday)
-- We use ISO DOW or just simple 1-7. Let's use text 'Monday', 'Tuesday' to be explicit and readable.

CREATE TABLE IF NOT EXISTS weekly_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) NOT NULL,
    day_of_week TEXT NOT NULL CHECK (day_of_week IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')),
    morning_role TEXT NOT NULL DEFAULT 'OFF' CHECK (morning_role IN ('ADMIN', 'RECEPTIONIST', 'SCANNER', 'OFF')),
    afternoon_role TEXT NOT NULL DEFAULT 'OFF' CHECK (afternoon_role IN ('ADMIN', 'RECEPTIONIST', 'SCANNER', 'OFF')),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, day_of_week)
);

-- Enable RLS
ALTER TABLE weekly_schedules ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read weekly_schedules" ON weekly_schedules FOR SELECT USING (true);
CREATE POLICY "Allow admin all weekly_schedules" ON weekly_schedules FOR ALL USING (true);


-- Ensure position_shifts handles upsert correctly via code, but RLS is fine.
-- (Previous migration created position_shifts, so we just use it)

-- Optional: Seed Admin Schedule for all days as ADMIN/ADMIN to prevent lockout if we weren't doing the bypass check.
-- But the bypass check is safer.
